
package net.coderodde.cskit;

import java.util.Arrays;
import java.util.Iterator;
import java.util.List;
import java.util.ListIterator;
import java.util.Map;
import java.util.Random;
import java.util.TreeMap;
import net.coderodde.cskit.Utilities.Pair;
import net.coderodde.cskit.Utilities.Triple;
import static net.coderodde.cskit.Utilities.Triple;
import static net.coderodde.cskit.Utilities.allWeakEquals;
import static net.coderodde.cskit.Utilities.debugPrintArray;
import static net.coderodde.cskit.Utilities.epsilonEquals;
import static net.coderodde.cskit.Utilities.generateSimpleGraph;
import static net.coderodde.cskit.Utilities.getPathCost;
import static net.coderodde.cskit.Utilities.getPresortedArray;
import static net.coderodde.cskit.Utilities.getRandomGraph;
import static net.coderodde.cskit.Utilities.getRandomIntegerArray;
import static net.coderodde.cskit.Utilities.isConnectedPath;
import static net.coderodde.cskit.Utilities.isSorted;
import static net.coderodde.cskit.Utilities.isSpanningTree;
import static net.coderodde.cskit.Utilities.line;
import static net.coderodde.cskit.Utilities.pathsAreSame;
import static net.coderodde.cskit.Utilities.spanningTreesEqual;
import static net.coderodde.cskit.Utilities.sumEdgeWeights;
import static net.coderodde.cskit.Utilities.title;
import static net.coderodde.cskit.Utilities.title2;
import net.coderodde.cskit.ds.list.TreeList;
import net.coderodde.cskit.ds.pq.BinaryHeap;
import net.coderodde.cskit.ds.pq.FibonacciHeap;
import net.coderodde.cskit.ds.pq.PriorityQueue;
import net.coderodde.cskit.ds.tree.OrderStatisticTree;
import net.coderodde.cskit.graph.DirectedGraphNode;
import net.coderodde.cskit.graph.DirectedGraphWeightFunction;
import net.coderodde.cskit.graph.UndirectedGraphEdge;
import net.coderodde.cskit.graph.UndirectedGraphNode;
import net.coderodde.cskit.graph.UndirectedGraphWeightFunction;
import net.coderodde.cskit.graph.flow.BidirectionalEdmondKarpFlowFinder;
import net.coderodde.cskit.graph.flow.EdmondKarpFlowFinder;
import net.coderodde.cskit.graph.flow.FlowFinder;
import net.coderodde.cskit.graph.mst.KruskalMSTFinder;
import net.coderodde.cskit.graph.mst.MinimumSpanningTreeFinder;
import net.coderodde.cskit.graph.mst.PrimMSTFinder;
import net.coderodde.cskit.graph.p2psp.general.AStarFinder;
import net.coderodde.cskit.graph.p2psp.general.BHPAFinder;
import net.coderodde.cskit.graph.p2psp.general.BidirectionalDijkstraFinder;
import net.coderodde.cskit.graph.p2psp.general.CoordinateMap;
import net.coderodde.cskit.graph.p2psp.general.DijkstraFinder;
import net.coderodde.cskit.graph.p2psp.general.EuclidianMetric;
import net.coderodde.cskit.graph.p2psp.general.FastSuboptimalFinder;
import net.coderodde.cskit.graph.p2psp.general.GeneralPathFinder;
import net.coderodde.cskit.graph.p2psp.general.WhangboFinder;
import net.coderodde.cskit.graph.p2psp.uniform.BreadthFirstSearchFinder;
import net.coderodde.cskit.graph.p2psp.uniform.BidirectionalBFSFinder;
import net.coderodde.cskit.graph.p2psp.uniform.ParallelBidirectionalBFSFinder;
import net.coderodde.cskit.graph.p2psp.uniform.UniformCostPathFinder;
import net.coderodde.cskit.sorting.BatchersSort;
import net.coderodde.cskit.sorting.CombSort;
import net.coderodde.cskit.sorting.CountingSort;
import net.coderodde.cskit.sorting.HeapSelectionSort;
import net.coderodde.cskit.sorting.HeapSort;